Repository WildCodeSchool/altermap-front, pull requests merged in 2020-01, with the labels that each got.

#27 Feature/react admin
  package-lock.json
  package.json
  public/manifest.json
  src/App.js
  src/components/Admin/Administrator.js
  src/components/Users/Users.js
Labels: Accept First

#33 Feature/css features
  src/components/Info/Info.css
  src/components/Info/Info.js
  src/components/Layers/Layers.css
  src/components/Layers/Layers.js
  src/components/Mapper/Mapper.js
  src/components/NavBar/NavBar.css
  src/components/PdfExport/PdfExport.css
  src/components/PdfExport/PdfExport.js
Labels: Accept 6

#35 Feature/jwt role
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.js
  src/components/Login/Login.js
  src/components/Mapper/Mapper.js
Labels: Accept First

#38 Add redirection to login when token is expired
  src/App.js
Labels: Accept Before

#40 Change theme in CSS not JSS ( see index.css )
  src/index.css
Labels: Accept 5

#37 Add log out button
  src/App.js
  src/components/Header/Header.css
  src/components/Header/Header.js
Labels: Accept 4
